import { FaHeading, FaParagraph } from "react-icons/fa";

export const textAlignList = ["left", "center", "right"];

export const fontFamilyList = [
  "Action Man Extended Bold Italic",
  "Action Man Extended Bold",
  "Action Man Extended Italic",
  "Action Man Extended",
  "Action Man Italic",
  "Action Man Shaded Italic",
  "Action Man Shaded",
  "Action Man",
  "Alfa Slab One",
  "Anton",
  "Antonio",
  "Avenir",
  "Bebas Neue",
  "Chalkduster",
  "Fira Sans Condensed Italic",
  "Fira Sans Condensed",
  "Fontjek",
  "Fredoka One",
  "Gotham Condensed",
  "Gotham Italic",
  "Gotham",
  "Koulen",
  "Lato Italic",
  "Lato",
  "Lobster",
  "Marker Felt",
  "Merriweather",
  "Montserrat",
  "Museo Slab",
  "Museo Slab Italic",
  "Oleo",
  "Ondfuturs",
  "Open Sans Condensed",
  "Open Sans Italic",
  "Open Sans",
  "Oswald",
  "Pacifico",
  "Poppins",
  "Poppins Italic",
  "Proxima Nova",
  "Roboto",
  "Satisfy",
  "Skranji",
];

export const textsElements = [
  {
    name: "Heading",
    icon: FaHeading,
    size: 40,
  },
  {
    name: "Paragraph",
    icon: FaParagraph,
    size: 20,
  },
];
